controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
etape1:
    path: /inscription
    controller: 'App\Controller\InscriptionController::etape1'

subscribe:
    path: /subscribe/
    controller: App\Controller\subscribeController::subscribe
subscribe2:
    path: /subscribe/2
    controller: App\Controller\subscribeController::subscribe2
subscribe3:
    path: /subscribe/3
    controller: App\Controller\subscribeController::subscribe3
subscribe4:
    path: /subscribe/4
    controller: App\Controller\subscribeController::subscribe4
account:
    path: /account
    controller: App\Controller\accountController::account
folder:
    path: /folder
    controller: App\Controller\folderController::folder

stripe_payment:
    path: /payment
    controller: App\Controller\PaymentController::stripePayment

payment_success:
    path: /payment/success
    controller: App\Controller\PaymentController::success